name: Common Continuous Integration tasks

on:
  workflow_call:
    outputs:
      build-artifact-id:
        description: "The build artifact id."
        value: ${{ jobs.continuous-integration.outputs.build-artifact-id }}
    secrets:
      ALGOLIA_API_KEY:
        required: true

permissions: {}

jobs:
  continuous-integration-prepare-docs:
    uses: hoverkraft-tech/ci-github-nodejs/.github/workflows/continuous-integration.yml@338755b95043af1f8aa17409529fd20a9d2ef659 # 0.20.6
    strategy:
      matrix:
        working-directory:
          - .github/actions/prepare-docs
          - .github/actions/generate-docs
    permissions:
      contents: read
      id-token: write
      packages: read
      pull-requests: write
      security-events: write
    with:
      working-directory: ${{ matrix.working-directory }}
      build: null
      lint: null
      dependency-review: false

  continuous-integration:
    uses: hoverkraft-tech/ci-github-nodejs/.github/workflows/continuous-integration.yml@338755b95043af1f8aa17409529fd20a9d2ef659 # 0.20.6
    permissions:
      contents: read
      id-token: write
      packages: read
      pull-requests: write
      security-events: write
    secrets:
      build-secrets: |
        ALGOLIA_API_KEY=${{ secrets.ALGOLIA_API_KEY }}
    with:
      working-directory: application
      build: |
        {
          "artifact": ["build"],
          "env": { "ALGOLIA_APP_ID": "${{ vars.ALGOLIA_APP_ID }}" }
        }
