name: Common Continuous Integration tasks

on:
  workflow_call:
    secrets:
      ALGOLIA_API_KEY:
        required: true

permissions:
  contents: read
  security-events: write
  # FIXME: This is a workaround for having workflow ref. See https://github.com/orgs/community/discussions/38659
  id-token: write

jobs:
  continuous-integration-prepare-docs:
    uses: hoverkraft-tech/ci-github-nodejs/.github/workflows/continuous-integration.yml@23af54bc615d657aa9c13c472ae701445c1811a6 # 0.17.1
    strategy:
      matrix:
        working-directory:
          - .github/actions/prepare-docs
          - .github/actions/generate-docs
    with:
      working-directory: ${{ matrix.working-directory }}
      build: null
      lint: false
      coverage: null
      dependency-review: false

  continuous-integration:
    uses: hoverkraft-tech/ci-github-nodejs/.github/workflows/continuous-integration.yml@23af54bc615d657aa9c13c472ae701445c1811a6 # 0.17.1
    secrets:
      build-secrets: |
        ALGOLIA_API_KEY=${{ secrets.ALGOLIA_API_KEY }}

    with:
      working-directory: application
      build: |
        {
          "artifact": ["application/build"],
          "env": { "ALGOLIA_APP_ID": "${{ vars.ALGOLIA_APP_ID }}" }
        }
